name: Clone Releases test

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          repository: andrewthetechie/gha-clone-releases
          ref: auth-download-assets
          path: gha-clone-releases
          token: ${{ secrets.THIS_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Update action.yml to use dockerfile
        uses: rmeneely/update-yaml@v1
        with:
          infile: gha-clone-releases/action.yml
          varlist: "runs.image=Dockerfile"
      - name: Clone Releases
        uses: ./gha-clone-releases
        with:
          token: ${{ secrets.THIS_PAT }}
          src_repo: andrewthetechie/test-private-repo
          copy_assets: true
